//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestHunter.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHDB : DbContext
    {
        public CHDB()
            : base("name=CHDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CONTEST> CONTESTs { get; set; }
        public DbSet<GROUP> GROUPs { get; set; }
        public DbSet<PROBLEM> PROBLEMs { get; set; }
        public DbSet<RECORD> RECORDs { get; set; }
        public DbSet<TESTDATA> TESTDATAs { get; set; }
        public DbSet<USER> USERs { get; set; }
    }
}
