//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestHunter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTEST
    {
        public CONTEST()
        {
            this.CONTEST_ATTEND = new HashSet<CONTEST_ATTEND>();
            this.PROBLEMs = new HashSet<PROBLEM>();
            this.RATINGs = new HashSet<RATING>();
            this.OWNERs = new HashSet<USER>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public bool IsOfficial { get; set; }
        public int Weight { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<CONTEST_ATTEND> CONTEST_ATTEND { get; set; }
        public virtual ICollection<PROBLEM> PROBLEMs { get; set; }
        public virtual ICollection<RATING> RATINGs { get; set; }
        public virtual ICollection<USER> OWNERs { get; set; }
    }
}
