//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestHunter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORD
    {
        public RECORD()
        {
            this.HUNTs = new HashSet<HUNT>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid User { get; set; }
        public System.Guid Problem { get; set; }
        public string Code { get; set; }
        public int Language { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public System.DateTime VirtualSubmitTime { get; set; }
        public Nullable<int> ExecutedTime { get; set; }
        public Nullable<long> MemoryUsed { get; set; }
        public int CodeLength { get; set; }
        public int Status { get; set; }
        public Nullable<int> Score { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<HUNT> HUNTs { get; set; }
        public virtual PROBLEM PROBLEM1 { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
