//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestHunter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        public SESSION()
        {
            this.MESSAGEs = new HashSet<MESSAGE>();
            this.USERs = new HashSet<USER>();
        }
    
        public System.Guid ID { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MESSAGE> MESSAGEs { get; set; }
        public virtual ICollection<USER> USERs { get; set; }
    }
}
