//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestHunter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTDATA
    {
        public System.Guid ID { get; set; }
        public System.Guid Problem { get; set; }
        public byte[] Input { get; set; }
        public byte[] Data { get; set; }
        public int TimeLimit { get; set; }
        public long MemoryLimit { get; set; }
    
        public virtual PROBLEM PROBLEM1 { get; set; }
    }
}
